# Generated by Django 3.0.3 on 2020-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mined_text',
            field=models.CharField(editable=False, max_length=500, null=True),
        ),
    ]
