# Generated by Django 3.0.3 on 2020-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWork', '0002_post_mined_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mined_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
